services:
  - type: web
    name: magical-database
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: NODE_ENV
        value: production
